### ISSUE TITLE
Method to submit back-ported patches?

### ISSUE THREAD

**Issue by keithj** [irods/irods-legacy#6]
There is a notice on this repository that pull requests will not be merged. What is the best route to submit patches to 3.3.1? Thanks.

**Comment by keithj** [comment]
Could the security fix from December that was posted on the wiki please be added as a commit?

**Comment by Wayne-Schroeder** [comment]
Sure, no problem.  I just committed it a few minutes ago.  As was our practice, the release file is still unchanged so people will need to apply the patch if they download the 3.3.1 release tar file (which they are still doing), but if they check the Downloads page they should see it. - Wayne -


-------- Original Message --------
Subject: Re: [irods-legacy] Method to submit back-ported patches? (#6)

**Comment by keithj** [comment]
Thanks, that's very helpful. We maintain a clone of irods-legacy from which we create our own releases.
